config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  
  get '/welcome/index'

  resources :invitations
  
  resources :trips do
    resources :comments
    resources :locations
  end
  
  resources :users
  post '/signup' => 'users#create'
  get '/login' => 'users#index'
  post '/login' => 'users#login'
  get '/logout' => 'users#destroy'
  
  

end

app/models/trip.rb
include ActionView::Helpers::SanitizeHelper
class Trip < ActiveRecord::Base

  has_many :trip_user_lists
  has_many :users
  belongs_to :user
  has_many :trip_user_lists
  has_many :comments

  before_save :sanitize_html

  protected
  def sanitize_html
    sanitized_output = sanitize("<script></script>")
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]


  # GET /trips
  # GET /trips.json
  def index
    if current_user
      trip_user_lists = TripUserList.all
      @trips = Trip.joins(:trip_user_lists).where('trip_user_lists.user_id' => session[:user_id])
      @invitations = Invitation.where(email: session[:user_email])
      @num_of_invites = @invitations.length
      render :index
    else
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'Please signup or login first.' }
      end
    end
    #joins(:trip_user_lists).where("trip_user_lists.user_id = session[:user_id]")
  end
  # GET /trips/1
  # GET /trips/1.json
  def show
    redirect_to trips_path
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    # binding.pry
    @trip = Trip.new(trip_params)
    respond_to do |format|
      if @trip.save
        @trip_user_list = TripUserList.new(trip_id: @trip.id,user_id: session[:user_id])
        # binding.pry
        @trip_user_list.save
        format.html { redirect_to "/trips/#{@trip.id}/locations", notice: 'Trip was successfully created.' }
      else
        format.html { render :index }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
      else
        format.html { render :index }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip_user_list = TripUserList.where(trip_id: @trip.id)
    @locations = Location.where(trip_id: @trip.id)
    respond_to do |format|
      if @trip.user_id == session[:user_id]
        @locations.each do |e|
          e.destroy
        end
        @trip_user_list.each do |e|
          e.destroy
        end
        @trip.destroy
        format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      else
        format.html { redirect_to trips_url, notice: 'You are not the creator of this trip.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      # binding.pry
      params['trip']['user_id'] = session[:user_id]
      params.require(:trip).permit(:name, :lat, :lng, :trip_date,  :description, :user_id)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>4
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :trip_date %><br>
    <%= f.text_field :trip_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<ol class="breadcrumb">
  <li class="active">My Trips</li>
</ol>

<%= content_tag :div, class: "trips_information", data: {trips: @trips} do %>
<% end %>

<script type="text/javascript">

  var map;
  var newyork_area = {lat: 40.7127, lng: -73.9059};
  var markers_trips = [];
  var myLatLng_trips = [];
  var labels_trip = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  var labelIndex_trip = 0;

  var trips_information = $('.trips_information').data('trips');

  for (var i = 0; i < trips_information.length; i++) {
    var latLng = {lat: parseFloat(trips_information[i].lat), lng: parseFloat(trips_information[i].lng)};
    myLatLng_trips.push(latLng);
  };

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      zoom: 10,
      center: newyork_area
    });
  }

  function drop() {
    clearMarkers();
    labelIndex_trip = 0;
    labels_trip = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    for (var i = 0; i < myLatLng_trips.length; i++) {
      addMarkerWithTimeout(myLatLng_trips[i], 200+i * 200);
    }
  }

  function addMarkerWithTimeout(position, timeout) {
    window.setTimeout(function() {
      markers_trips.push(new google.maps.Marker({
        position: position,
        map: map,
        label: labels_trip[labelIndex_trip++ % labels_trip.length],
        animation: google.maps.Animation.DROP
      }));
    }, timeout);
  }

  function clearMarkers() {
    for (var i = 0; i < markers_trips.length; i++) {
      markers_trips[i].setMap(null);
    }
    markers_trips = [];
  }

  document.onload = drop();

</script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfDMuS-T8EaT1i_72vzMG181Qm4GyXXos&callback=initMap">
</script>

<div id="map">
</div>
<!-- <div class="trip_search">
    <div class="input-group">
      <input type="text" class="form-control" id="trip_search_input"placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-default" id="trip_search" type="button">Go!</button> -->

<form class="trip_search">
    <input type="text" class="trip_search_input" id="trip_search_input">
    <button type="submit" id="trip_search" class="pure-button">Search</button>
</form>

<div class="dropup trip_list">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <p>Trip List &#9776;<p>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
    
    <div class="panel panel-default">
    <div class="panel-heading">My Trips</div>
    <!-- <div class="trip_list"> -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Trip</th>
            <th>Trip Date</th>
            <th>Creator</th>
            <th>Description</th>
            <th>Comments</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @trips.each do |trip| %>
            <tr>
              <td><%= link_to trip.name , trip_locations_path(trip)%></td>
              <td><%= trip.trip_date %></td>
              <td><%= trip.user.name %></td>
              <td><%= trip.description %></td>
              <td><a href=<%= trip_comments_path(trip) %>><span class="badge"><%= trip.comments.length %></span></a></td>
              <td><%= link_to 'Remove Trip', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!-- </div> -->
 
  </ul>
</div>

<div class="trip_form">
  <div class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <p>Add Trip &#9776;<p>
  </div>
  <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenu1">
    <%= form_for :trip, url: '/trips' do |f| %>
      Name: <%= f.text_field :name %> <br>
      Lat: <%= f.text_field :lat %> <br>
      Lng: <%= f.text_field :lng %> <br>
      Description: <%= f.text_field :description %> <br>
      Trip_date: <%= f.text_field :trip_date %> <br>
      <button type="submit" id="create_trip" class="create_trip">Create</button>
    <% end %>
  </ul>
</div>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<% lat = 20 %>
<%= @trip.name %>
<div id="map"></div>

<script type="text/javascript">
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @trip.lat %>, lng: <%= @trip.lng %>},
      zoom: 15
    });
  }
  // var marker = new google.maps.Marker({
  //   var myLatLng = {lat: <%= @trip.lat %>, lng: <%= @trip.lng %>}
  //     position: myLatLng,
  //     map: map,
  //     title: 'Hello World!'
  //   });
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfDMuS-T8EaT1i_72vzMG181Qm4GyXXos&callback=initMap">
</script>

<h3>Search for a location to add</h3>
<form class="location_search">
  <input type="text" class="location_search_input" id="location_search_input">
  <button type="submit" id="location_search" class="pure-button">Search</button>
</form>
    <h3>Add a destination for your trip!</h3>
<form class="location_form" id="location_form" method = "POST">
  <label>Address:</label>
  <input type="text" class="location_address" id="location_address"><br>
  <label>Venue Notes:</label>
  <input type="text" class="location_notes" id="location_notes"><br>
  <button type="submit" id="create_pin" class="create_pin">Pin It</button>
</form>

<!-- <p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @trip.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @trip.lng %>
</p>

<p>
  <strong>Trip date:</strong>
  <%= @trip.trip_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user %>
</p>
 -->
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>