config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  
  get '/welcome/index'

  resources :invitations
  
  resources :trips do
    resources :comments
    resources :locations
  end
  
  resources :users
  post '/signup' => 'users#create'
  get '/login' => 'users#index'
  post '/login' => 'users#login'
  get '/logout' => 'users#destroy'
  
  

end

app/models/comment.rb
include ActionView::Helpers::SanitizeHelper
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
  before_save :sanitize_html

  protected
  def sanitize_html
    sanitized_output = sanitize("<script></script>")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @trip = Trip.find(params[:trip_id])
    @comments = Comment.where(trip_id: params[:trip_id])
    @num_of_comments = @comments.length
    @invitations = Invitation.where(email: session[:user_email])
    @num_of_invites = @invitations.length
  end
 
  # GET /comments/1
  # GET /comments/1.json
  def show
    redirect_to trip_comments_url
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.find(params[:id])
    @invitations = Invitation.where(email: session[:user_email])
    @num_of_invites = @invitations.length
  end

  # GET /comments/new
  def new
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.new
    @invitations = Invitation.where(email: session[:user_email])
    @num_of_invites = @invitations.length
  end
 
  # GET /comments/1/edit
  def edit
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.find(params[:id])
    @invitations = Invitation.where(email: session[:user_email])
    @num_of_invites = @invitations.length
  end

  # POST /comments
  # POST /comments.json
  def create
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.new(comment_params)
    # binding.pry
    respond_to do |format|
      if @comment.save
        format.html { redirect_to trip_comments_url, notice: 'Comment was successfully created.' }
        format.json { render :index, status: :created, location: [@trip,@comment] }
      else
        format.html { render :index }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.find(params[:id])  
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to trip_comments_url, notice: 'Comment was successfully updated.' }
        format.json { render :index, status: :ok, location: [@trip,@comment] }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @trip = Trip.find(params[:trip_id])
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @trip.user_id == session[:user_id]
        @comment.destroy
        format.html { redirect_to trip_comments_url, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to trip_comments_url, notice: 'You are not the creator of this comment.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      if params[:trip_id]
        @comment = Comment.where(params[:trip_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params['comment']['user_id'] = session[:user_id]
      params['comment']['trip_id'] = params[:trip_id]
      # binding.pry
      params.require(:comment).permit(:comment, :user_id, :trip_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@trip, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<ol class="breadcrumb">
  <li><a href="/trips">My Trips</a></li>
  <li><a href="/trips/<%= params[:trip_id]%>"><%= @trip.name %></a></li>
  <li class="active">Comments</li>
</ol>
<div class="container">
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', trip_comment_path(@trip,@comment) %> |
<%= link_to 'Back', trip_comments_path %>
</div>

app/views/comments/index.html.erb
<ol class="breadcrumb">
  <li><a href="/trips">My Trips</a></li>
  <li><a href="/trips/<%= params[:trip_id]%>"><%= @trip.name %></a></li>
  <li class="active">Comments</li>
</ol>
  
<center>
<button type="button" class="btn btn-secondary"><%= link_to 'New Comment', new_trip_comment_path(@trip) %></button>
  
</center>
<div class="comments">

    <% @comments.each do |comment| %>
    <div class="col-md-12">
      <div class="row">
        <div class="col-sm-3">
          <img src="<%=comment.user.image_url%>" class="img-rounded" width="100" height="auto">
          <h5>Created by: <%=comment.user.name%></h5>
        </div>
        <div class="col-sm-6">
          <div class="jumbotron"><%= comment.comment %></div>
        </div>
        <div class="col-sm-3">
          <br>
          <%= link_to 'New Comment', new_trip_comment_path(@trip) %>
          <br>
          <%= link_to 'Edit', edit_trip_comment_path(@trip,comment) %>
          <br>
          <%= link_to 'Destroy', trip_comment_path(@trip,comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>   
          
        
    <% end %>
</div>

app/views/comments/new.html.erb
<ol class="breadcrumb">
  <li><a href="/trips">My Trips</a></li>
  <li><a href="/trips/<%= params[:trip_id]%>"><%= @trip.name %></a></li>
  <li class="active">Comments</li>
</ol>

<div class="container">
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', trip_comments_path %>
</div>

app/views/comments/show.html.erb
<ol class="breadcrumb">
  <li><a href="/trips">My Trips</a></li>
  <li><a href="/trips/<%= params[:trip_id]%>"><%= @trip.name %></a></li>
  <li><a href="/trips/<%= params[:trip_id]%>/comments"><%= @trip.name %> Comments</a></li>
  <li class="active">Comment</li>
</ol>
<div class="container">
<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @comment.trip.name %>
</p>
<%= link_to 'Edit', edit_trip_comment_path(@trip, @comment) %> |
<%= link_to 'Back', trip_comments_path %>
</div>