config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  
  get '/welcome/index'

  resources :invitations
  
  resources :trips do
    resources :comments
    resources :locations
  end
  
  resources :users
  post '/signup' => 'users#create'
  get '/login' => 'users#index'
  post '/login' => 'users#login'
  get '/logout' => 'users#destroy'
  
  

end

app/models/location.rb
include ActionView::Helpers::SanitizeHelper
class Location < ActiveRecord::Base
  belongs_to :trip
  belongs_to :user
  before_save :sanitize_html

  protected
  def sanitize_html
    sanitized_output = sanitize("<script></script>")
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  # GET /locations
  def index
    # binding.pry
    @locations = Location.where(trip_id: params[:trip_id])
    @trip = Trip.find(params[:trip_id])
    @location = Location.new
    @invitations = Invitation.where(email: session[:user_email])
    @num_of_invites = @invitations.length
  end


  # POST /locations
  def create
    @trip = Trip.find(params[:trip_id])
    @location = Location.new(location_params)
    @location.save
    @locations = Location.where(trip_id: params[:trip_id])
    redirect_to trip_locations_path(@trip,@locations)
  end

  # DELETE /locations/1
  def destroy
    @trip = Trip.find(params[:trip_id])
    @location = Location.find(params[:id])
    @location.destroy
    respond_to do |format|
      format.html { redirect_to [@trip,@location], notice: 'Location was successfully destroyed.' }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params['location']['user_id'] = session[:user_id]
      params['location']['trip_id'] = params[:trip_id]
      params.require(:location).permit(:loc_lng, :loc_lat, :address, :venue, :trip_id, :user_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :loc_long %><br>
    <%= f.text_field :loc_long %>
  </div>
  <div class="field">
    <%= f.label :loc_lat %><br>
    <%= f.text_field :loc_lat %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.text_field :trip_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<ol class="breadcrumb">
  <li><a href="/trips">My Trips</a></li>
  <li class="active"><%= @trip.name %></li>
</ol>

<%= content_tag :div, class: "locations_information", data: {locations: @locations} do %>
<% end %>

<div id="map"></div>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfDMuS-T8EaT1i_72vzMG181Qm4GyXXos&callback=initMap">
</script>

<script type="text/javascript">
  var map;

  var markers_locations=[];
  var marker_location;
  var markers_temp = {};
  var addMarker;
  var labels_location = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  var labelIndex_location = 0;
  var myLatLng_location=[];

  var locations_information = $('.locations_information').data('locations');

  for (var i = 0; i < locations_information.length; i++) {
    var latLng = {lat: parseFloat(locations_information[i].loc_lat), lng: parseFloat(locations_information[i].loc_lng)};
    myLatLng_location.push(latLng);
  };

  function initMap() {

    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @trip.lat %>, lng: <%= @trip.lng %>},
      zoom: 15
    });
    // This event listener calls addMarker() when the map is clicked.
    google.maps.event.addListener(map, 'click', function(event) {
      addMarker(event.latLng, map);
    });

  }//initMaps


  function drop() {
    clearMarkers();
    labelIndex_location = 0;
    labels_location = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    for (var i = 0; i < myLatLng_location.length; i++) {
      addMarkerWithTimeout(myLatLng_location[i], 200+i * 200);
    }
  }

  function addMarkerWithTimeout(position, timeout) {
    window.setTimeout(function() {
      markers_locations.push(new google.maps.Marker({
        position: position,
        label: labels_location[labelIndex_location++ % labels_location.length],
        map: map,
        animation: google.maps.Animation.DROP
      }));
    }, timeout);
  }

  function clearMarkers() {
    for (var i = 0; i < markers_locations.length; i++) {
      markers_locations[i].setMap(null);
    }
    markers_locations = [];
  }

  document.onload = drop();

  var getMarkerUniqueId= function(lat, lng) {
    return lat + '_' + lng;
  }

  var getLatLng = function(lat, lng) {
    return new google.maps.LatLng(lat, lng);
  };

  function addMarker(location, map) {
  // Add the marker at the clicked location, and add the next-available label
  // from the array of alphabetical characters.
    var lat = location.lat(); // lat of clicked point
    var lng = location.lng(); // lng of clicked point
    var markerId = getMarkerUniqueId(lat, lng); // this will be used to cache this marker in markers_temp object.

    marker_location = new google.maps.Marker({
      position: getLatLng(lat, lng),
      label: labels_location[labelIndex_location++ % labels_location.length],
      map: map,
      draggable:true,
      id: 'marker_' + markerId
    });
    
    $('#location_loc_lat').val(lat);
    $('#location_loc_lng').val(lng);

    google.maps.event.addListener(marker_location, 'dragend', function(ev){
      lat = marker_location.getPosition().lat();
      lng = marker_location.getPosition().lng();
      $('#location_loc_lat').val(lat);
      $('#location_loc_lng').val(lng);
    });

    markers_temp[markerId] = marker_location; // cache marker in markers object
    bindMarkerEvents(marker_location); // bind right click event to marker

    markers_locations.push(marker_location);

  }//add markers

  var bindMarkerEvents = function(markers_locations) {
    google.maps.event.addListener(markers_locations, "rightclick", function (point) {
        var markerId = getMarkerUniqueId(point.latLng.lat(), point.latLng.lng()); // get marker id by using clicked point's coordinate
        var markers_locations = markers_temp[markerId]; // find marker
        removeMarker(markers_locations, markerId); // remove it
    });
  };

  var removeMarker = function(markers_locations, markerId) {
    markers_locations.setMap(null); // set markers setMap to null to remove it from map
    delete markers_temp[markerId]; // delete marker instance from markers object
  };

  // google.maps.event.addDomListener(window, 'load', initMap);

</script>

<div class="dropup location_list">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <p>Location List &#9776;<p>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Address</th>
          <th>Venue</th>
          <th>Pin Dropper</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @locations.each do |location| %>
          <tr>
            <td><%= location.address %></td>
            <td><%= location.venue %></td>
            <td><%= location.user.name %></td>
            <td><%= link_to 'Delete', trip_location_path(@trip,location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </ul>
</div>

<div class="trip_form">
  <div class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    <p>Add Location &#9776;<p>
  </div>
  <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenu1">
  <%= form_for :location, url: trip_locations_path(@trip,@locations) do |f| %>
    Loc_lat: <%= f.text_field :loc_lat %> <br>
    Loc_lng: <%= f.text_field :loc_lng %> <br>
    Address: <%= f.text_field :address %> <br>
    Venue: <%= f.text_field :venue %> <br>
    <button type="submit" id="create_trip" class="create_trip">Create</button>
  <% end %>
  <%= link_to 'Back to Trip Plan', trips_path %>
  </ul>
</div>

app/views/locations/new.html.erb
<!-- <p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @trip.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @trip.lng %>
</p>

<p>
  <strong>Trip date:</strong>
  <%= @trip.trip_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user %>
</p>
 -->
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

<!-- 
<%= render 'form' %>

<%= link_to 'Back', locations_path %> -->

app/views/locations/show.html.erb
<h1>New Location</h1>

<% lat = 20 %>

<div id="map"></div>

<script type="text/javascript">
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @trip.lat %>, lng: <%= @trip.lng %>},
      zoom: 15
    });
  }
  // var marker = new google.maps.Marker({
  //   var myLatLng = {lat: <%= @trip.lat %>, lng: <%= @trip.lng %>}
  //     position: myLatLng,
  //     map: map,
  //     title: 'Hello World!'
  //   });
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfDMuS-T8EaT1i_72vzMG181Qm4GyXXos&callback=initMap">
</script>

<h3>Search for a location to add</h3>
<form class="location_search">
  <input type="text" class="location_search_input" id="location_search_input">
  <button type="submit" id="location_search" class="pure-button">Search</button>
</form>
    <h3>Add a destination for your trip!</h3>
<form class="location_form" id="location_form" method = "POST">
  <label>Address:</label>
  <input type="text" class="location_address" id="location_address"><br>
  <label>Venue Notes:</label>
  <input type="text" class="location_notes" id="location_notes"><br>
  <button type="submit" id="create_pin" class="create_pin">Pin It</button>
</form>

<!-- <p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @trip.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @trip.lng %>
</p>

<p>
  <strong>Trip date:</strong>
  <%= @trip.trip_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user %>
</p>
 -->
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>